[package]
name = "priority_queue"
version = "0.1.0"
edition = "2021"
authors = ["Nate <npcompletenate@protonmail.com>"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
